"""initial

Revision ID: 6bbc60fcbf76
Revises: 
Create Date: 2025-06-26 21:18:32.552740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 # add geoalchemy to the migration file


# revision identifiers, used by Alembic.
revision: str = '6bbc60fcbf76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'timestamp')
    )
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_locations_session_id'), 'locations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_session_id'), table_name='locations')
    op.drop_index('idx_locations_geom', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    # ### end Alembic commands ###
