"""add columns for duration

Revision ID: 74ca75936791
Revises: 9f3af74762c8
Create Date: 2025-07-10 16:40:52.128588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 # add geoalchemy to the migration file


# revision identifiers, used by Alembic.
revision: str = '74ca75936791'
down_revision: Union[str, Sequence[str], None] = '9f3af74762c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_sessions', sa.Column('duration_s_active', sa.Float(), nullable=True))
    op.add_column('track_sessions', sa.Column('duration_s_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_sessions', 'duration_s_total')
    op.drop_column('track_sessions', 'duration_s_active')
    # ### end Alembic commands ###
