"""add users and track sessions

Revision ID: a79a951fe69f
Revises: 6e735193a8d2
Create Date: 2025-06-27 23:10:09.286606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 # add geoalchemy to the migration file
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a79a951fe69f'
down_revision: Union[str, Sequence[str], None] = '6e735193a8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_table('track_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'start_timestamp')
    )
    op.create_index(op.f('ix_track_sessions_session_id'), 'track_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_track_sessions_user_id'), 'track_sessions', ['user_id'], unique=False)
    op.add_column('locations', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.drop_column('locations', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('locations', 'is_paused')
    op.drop_index(op.f('ix_track_sessions_user_id'), table_name='track_sessions')
    op.drop_index(op.f('ix_track_sessions_session_id'), table_name='track_sessions')
    op.drop_table('track_sessions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
